apiVersion: v1
baseDomain: clientcenter.local
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 10
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 5
metadata:
  name: ocp4prod
networking:
  clusterNetworks:
  - cidr: 10.254.0.0/16
    hostPrefix: 24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 192.168.0.0/16
platform:
  vsphere:
    vcenter: 
    username: 
    password: 
    datacenter: 
    defaultDatastore: 

pullSecret: 

sshKey: 

